name: spiccato
description: Application for listening some music or podcasts on desktop.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: IBM
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: fonts/IBMPlexSans-Bold.ttf
          weight: 700
