name: spiccato
description: Application for listening some music or podcasts on desktop.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.5
  dart_vlc: ^0.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
  linux:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: IBM
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: fonts/IBMPlexSans-Bold.ttf
          weight: 700
